a = ['An older man dressed in blue historical clothing is ringing a bell in his right hand.',
     'A man sitting in a barber shop.',
     'Others complain that the superstars are over the hill, and are trotting out mediocre work.',
     'Two elderly people sing in microphones while playing instruments.', 'A white bike is tied to a street sign.',
     'uh-huh do you work out on like is it the weight machines or aerobics or what is it',
     "uh i'm i'm not real sure that the young girls of today are being forced into the job market as many of them imply i think they're going in by choice",
     'Analysis of this information revealed that no two of these organizations defined the design review process and its various elements in exactly the same manner.',
     "yeah i don't mind the heat that much it doesn't bother me that much cold weather i just i don't know i just can't tolerate too much with the",
     "you know used to play it a lot when i was in school but  now that i'm married and stuff i",
     'a woman with a straw hat working on a strange machine with coconuts at her side.',
     'Alternatively, he could have used his address to the Christian Coalition last Friday to criticize religious intolerance.',
     'Two pre-teen girls listening to music on an MP3 player with headphones.',
     'Woman walking by a mural of an old bald man.', 'White looked up at me, quite slowly.',
     'A dog is preparing to run away from a person interacting with it.',
     "There's a sort of bidding war going on, with law schools offering ever-increasing financial packages -- most of it loans, said Dean Glen. ",
     'This was-and remains-an enormous challenge.', 'Women exercising one woman has a green mat and black outfit on.',
     'A man in a tan suit is using a pay phone to make a call.',
     'Rock, Folk, and  The Royal Dublin Society in Ballsbridge holds huge open-air concerts, including rock, folk, and jazz.',
     'Table 7-1 shows a summary of resource demand and its effect on current supply.',
     "This major initiative, conceived by Supreme Court Justice Anthony M. Kennedy, is the American Bar Association's principal Law Day outreach this year.",
     "This is the most easily accessible of the New Territories' walled villages.",
     "I'm in a huge, overwhelming sea of debt, said Jennifer Arons, 28, a criminal defense staff attorney at Manhattan Legal Aid. ",
     'Acidic deposition or acid rain occurs when SO2 and NOx in the atmosphere react with water, oxygen, and oxidants to form acidic compounds.',
     'Group of people dancing', 'A woman and a few children in an alleyway in between a vehicle and a fence.',
     'okay uh are you in the market for a new car', "so let's see what well what kind of music do you not like",
     'His manner was unfortunate, I observed thoughtfully. ', 'but uh because i work for uh Hal Ammon',
     'A girl in a green sweatshirt sitting down and a girl in a dress leaning on blue lockers.',
     'a brown dog is jumping up at a woman who is wearing a brown skirt.', 'Stop blaming John.',
     'This analysis pooled estimates from these two studies to develop a C-R function linking PM to chronic bronchitis.',
     'Woman on airplane models a flotation device.', 'A black dog swimming in water near rocks.',
     'A man being airlifted to safety after being in danger.',
     'Nor have the rich maintained that audible indicator, that quasi-English, quasi-lockjawed accent that the swells all had in Depression-era movies.',
     'In this paper we examine the hypothesis that the cost model provides reasonable estimates of the unit costs of other posts of industrialized countries.',
     'A motocross biker about to descend', 'It was dead quiet.',
     ' Elsewhere, great events were changing the shape of the world.',
     'A man wearing a blue shirt is sitting on a brick planter next to some paintings.',
     'Small blond-haired girl drinking a glass of juice.',
     'The nurse smiles as she gently rubs the tummy of the sleeping child.',
     ]
